name: moe
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # State management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  # Google fonts
  google_fonts: ^6.2.1
  # Dependency Injection
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  # Dot env
  flutter_dotenv: ^5.1.0
  # QR Scanner
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env